const productsData = [{
        id: 1,
        image: "images/products/Assouplissant 1L.jpg",
        title: "Assouplissant 1L",
        buttons: [{
                btnClass: "mixed-colors",
                btnText: "",
                btnData: "images/products/Assouplissant 1L.jpg",
                btnDataText: "Assouplissant 1L",
            },
            {
                btnClass: "ocean-blue",
                btnText: "",
                btnData: "images/products/Assouplissant 1L Blue.jpg",
                btnDataText: "Assouplissant 1L Ocean",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Assouplissant 1L Green.jpg",
                btnDataText: "Assouplissant 1L Printemps",
            },
            {
                btnClass: "pink-floral",
                btnText: "",
                btnData: "images/products/Assouplissant 1L Pink.jpg",
                btnDataText: "Assouplissant 1L Floral",
            },
            {
                btnClass: "purple-classic",
                btnText: "",
                btnData: "images/products/Assouplissant 1L Purple.jpg",
                btnDataText: "Assouplissant 1L Classic",
            },
            {
                btnClass: "white-nature",
                btnText: "",
                btnData: "images/products/Assouplissant 1L White.jpg",
                btnDataText: "Assouplissant 1L Nature",
            },
        ],
    },
    {
        id: 2,
        image: "images/products/Assouplissant 5L.jpg",
        title: "Assouplissant 5L",
        buttons: [{
                btnClass: "mixed-colors",
                btnText: "",
                btnData: "images/products/Assouplissant 5L.jpg",
                btnDataText: "Assouplissant 5L",
            },
            {
                btnClass: "ocean-blue",
                btnText: "",
                btnData: "images/products/Assouplissant 5L Blue.jpg",
                btnDataText: "Assouplissant 5L Ocean",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Assouplissant 5L Green.jpg",
                btnDataText: "Assouplissant 5L Printemps",
            },
            {
                btnClass: "pink-floral",
                btnText: "",
                btnData: "images/products/Assouplissant 5L Pink.jpg",
                btnDataText: "Assouplissant 5L Floral",
            },
            {
                btnClass: "purple-classic",
                btnText: "",
                btnData: "images/products/Assouplissant 5L Purple.jpg",
                btnDataText: "Assouplissant 5L Classic",
            },
            {
                btnClass: "white-nature",
                btnText: "",
                btnData: "images/products/Assouplissant 5L White.jpg",
                btnDataText: "Assouplissant 5L Nature",
            },
        ],
    },
    {
        id: 3,
        image: "images/products/Grizel 5L.jpg",
        title: "Grizel 5L",
        buttons: [{
                btnClass: "mixed-colors",
                btnText: "",
                btnData: "images/products/Grizel 5L.jpg",
                btnDataText: "Grizel 5L",
            },
            {
                btnClass: "ocean-blue",
                btnText: "",
                btnData: "images/products/Grizel 5L Blue.jpg",
                btnDataText: "Grizel 5L Lavande",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Grizel 5L Green.jpg",
                btnDataText: "Grizel 5L Pin",
            },
            {
                btnClass: "pink-floral",
                btnText: "",
                btnData: "images/products/Grizel 5L Pink.jpg",
                btnDataText: "Grizel 5L Rose",
            },
            {
                btnClass: "white-nature",
                btnText: "",
                btnData: "images/products/Grizel 5L White.jpg",
                btnDataText: "Grizel 5L Bouquet",
            },
        ],
    },
    {
        id: 4,
        image: "images/products/Grizel 90Cl.jpg",
        title: "Grizel 90Cl",
        buttons: [{
                btnClass: "mixed-colors",
                btnText: "",
                btnData: "images/products/Grizel 90Cl.jpg",
                btnDataText: "Grizel 90Cl",
            },
            {
                btnClass: "ocean-blue",
                btnText: "",
                btnData: "images/products/Grizel 90Cl Blue.jpg",
                btnDataText: "Grizel 90Cl Lavande",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Grizel 90Cl Green.jpg",
                btnDataText: "Grizel 90Cl Pin",
            },
            {
                btnClass: "pink-floral",
                btnText: "",
                btnData: "images/products/Grizel 90Cl Pink.jpg",
                btnDataText: "Grizel 90Cl Rose",
            },
            {
                btnClass: "white-nature",
                btnText: "",
                btnData: "images/products/Grizel 90Cl White.jpg",
                btnDataText: "Grizel 90Cl Bouquet",
            },
        ],
    },
    {
        id: 5,
        image: "images/products/Extra 650ml.jpg",
        title: "Super Extra 650ml carton de 12",
        buttons: [{
                btnClass: "green-yellow",
                btnText: "",
                btnData: "images/products/Extra 650ml.jpg",
                btnDataText: "Super Extra 650ml carton de 12",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Extra 650ml Green.jpg",
                btnDataText: "Super Extra 650ml Pomme carton de 12",
            },
            {
                btnClass: "yellow-citron",
                btnText: "",
                btnData: "images/products/Extra 650ml Yellow.jpg",
                btnDataText: "Super Extra 650ml Citron carton de 12",
            },
        ],
    },
    {
        id: 6,
        image: "images/products/Multiusage.jpg",
        title: "Vaiselle Multiusage 5L",
        buttons: [{
                btnClass: "green-yellow",
                btnText: "",
                btnData: "images/products/Multiusage.jpg",
                btnDataText: "Vaiselle Multiusage 5L",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Multiusage Green.jpg",
                btnDataText: "Vaiselle Multiusage 5L Pomme",
            },
            {
                btnClass: "yellow-citron",
                btnText: "",
                btnData: "images/products/Multiusage Yellow.jpg",
                btnDataText: "Vaiselle Multiusage 5L Citron",
            },
        ],
    },
    {
        id: 7,
        image: "images/products/Vaisselle 5L.jpg",
        title: "Vaiselle 5L",
        buttons: [{
                btnClass: "green-yellow",
                btnText: "",
                btnData: "images/products/Vaisselle 5L.jpg",
                btnDataText: "Vaisselle 5L",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Vaisselle 5L Green.jpg",
                btnDataText: "Vaisselle 5L Pomme",
            },
            {
                btnClass: "yellow-citron",
                btnText: "",
                btnData: "images/products/Vaisselle 5L Yellow.jpg",
                btnDataText: "Vaisselle 5L Citron",
            },
        ],
    },
    {
        id: 8,
        image: "images/products/Vaisselle 90Cl.jpg",
        title: "Vaiselle 90cl",
        buttons: [{
                btnClass: "green-yellow",
                btnText: "",
                btnData: "images/products/Vaisselle 90Cl.jpg",
                btnDataText: "Vaiselle 90cl",
            },
            {
                btnClass: "green-spring",
                btnText: "",
                btnData: "images/products/Vaisselle 90Cl Green.jpg",
                btnDataText: "Vaisselle 90cl Pomme de 6",
            },
            {
                btnClass: "yellow-citron",
                btnText: "",
                btnData: "images/products/Vaisselle 90Cl Yellow.jpg",
                btnDataText: "Vaisselle 90cl Citron de 6",
            },
        ],
    },
    {
        id: 9,
        image: "images/products/Extra 2L Yellow.jpg",
        title: "Vaiselle Extra 2L carton de 12 Citron",
        buttons: [{
                btnClass: "capacity",
                btnText: "2L",
                btnData: "images/products/Extra 2L Yellow.jpg",
                btnDataText: "Vaiselle Extra 2L carton de 12 Citron",
            },
            {
                btnClass: "capacity",
                btnText: "1L",
                btnData: "images/products/Extra 1L Yellow.jpg",
                btnDataText: "Vaiselle Extra 1L carton de 12 Citron",
            },
        ],
    },
    {
        id: 10,
        image: "images/products/Extra 2L Green.jpg",
        title: "Vaiselle Extra 2L carton de 12 Pomme",
        buttons: [{
                btnClass: "capacity",
                btnText: "2L",
                btnData: "images/products/Extra 2L Green.jpg",
                btnDataText: "Vaiselle Extra 2L carton de 12 Pomme",
            },
            {
                btnClass: "capacity",
                btnText: "1L",
                btnData: "images/products/Extra 1L Green.jpg",
                btnDataText: "Vaiselle Extra 1L carton de 12 Pomme",
            },
        ],
    },
    {
        id: 11,
        image: "images/products/Gel WC.jpg",
        title: "Gel WC Carton de 12",
        buttons: [{
                btnClass: "capacity",
                btnText: "500ml",
                btnData: "images/products/Gel WC 500ml.jpg",
                btnDataText: "Gel WC 500ml Carton de 12",
            },
            {
                btnClass: "capacity",
                btnText: "750ml",
                btnData: "images/products/Gel WC 750ml.jpg",
                btnDataText: "Gel WC 750ml Carton de 10",
            },
        ],
    },
    {
        id: 12,
        image: "images/products/Javel.jpg",
        title: "Javel",
        buttons: [{
                btnClass: "capacity",
                btnText: "5L",
                btnData: "images/products/Javel 5L.jpg",
                btnDataText: "Javel 5L",
            },
            {
                btnClass: "capacity",
                btnText: "3L",
                btnData: "images/products/Javel 3L.jpg",
                btnDataText: "Javel 3L",
            },
            {
                btnClass: "capacity",
                btnText: "90cl",
                btnData: "images/products/Javel 90CL.jpg",
                btnDataText: "Javel 90CL de 6",
            },
        ],
    },
    {
        id: 13,
        image: "images/products/Lessive Automatique.jpg",
        title: "Lessive Automatique",
        buttons: [{
                btnClass: "capacity",
                btnText: "5L",
                btnData: "images/products/Lessive Automatique 5L.jpg",
                btnDataText: "Lessive Automatique 5L",
            },
            {
                btnClass: "capacity",
                btnText: "3L",
                btnData: "images/products/Lessive Automatique 3L.jpg",
                btnDataText: "Lessive Automatique 3L",
            },
        ],
    },
    {
        id: 14,
        image: "images/products/Rapido Lessive Liquide Green.jpg",
        title: "Rapido lessive liquide Vert",
        buttons: [{
                btnClass: "capacity",
                btnText: "5L",
                btnData: "images/products/Rapido Lessive Liquide 5L Green.jpg",
                btnDataText: "Rapido lessive liquide 5L Vert",
            },
            {
                btnClass: "capacity",
                btnText: "3L",
                btnData: "images/products/Rapido Lessive Liquide 3L Green.jpg",
                btnDataText: "Rapido lessive liquide 3L Vert",
            },
        ],
    },
    {
        id: 15,
        image: "images/products/Rapido Lessive Liquide White.jpg",
        title: "Rapido lessive liquide Blanc",
        buttons: [{
                btnClass: "capacity",
                btnText: "5L",
                btnData: "images/products/Rapido Lessive Liquide 5L White.jpg",
                btnDataText: "Rapido lessive liquide 5L Blanc",
            },
            {
                btnClass: "capacity",
                btnText: "3L",
                btnData: "images/products/Rapido Lessive Liquide 3L White.jpg",
                btnDataText: "Rapido lessive liquide 3L Blanc",
            },
        ],
    },
    {
        id: 16,
        image: "images/products/Rapido Lessive Special Tapis.jpg",
        title: "Rapido lessive Spécial tapis Rose",
        buttons: [{
                btnClass: "capacity",
                btnText: "5L",
                btnData: "images/products/Rapido Lessive Special Tapis 5L.jpg",
                btnDataText: "Rapido lessive Spécial tapis 5L Rose",
            },
            {
                btnClass: "capacity",
                btnText: "3L",
                btnData: "images/products/Rapido Lessive Special Tapis 3L.jpg",
                btnDataText: "Rapido lessive Spécial tapis 3L Rose",
            },
            {
                btnClass: "capacity",
                btnText: "3L Blanc",
                btnData: "images/products/Rapido Lessive Special Tapis 3L White.jpg",
                btnDataText: "Rapido lessive Spécial tapis 3L Blanc",
            },
        ],
    },
    {
        id: 17,
        image: "images/products/Liquide Moussant 100ml.jpg",
        title: "Alto Liquide Moussant 100ml carton de 12 [Péche, Aloevera, Lavande, Fruit Rouge]",
        buttons: [{
                btnClass: "capacity",
                btnText: "100ml",
                btnData: "images/products/Liquide Moussant 100ml.jpg",
                btnDataText: "Alto Liquide Moussant 100ml carton de 12 [Péche, Aloevera, Lavande, Fruit Rouge]",
            },
            {
                btnClass: "capacity",
                btnText: "500ml",
                btnData: "images/products/Liquide Moussant 500ml.jpg",
                btnDataText: "Alto Liquide Moussant 500ml",
            },
        ],
    },
    {
        id: 18,
        image: "images/products/Rapido Shampoing.jpg",
        title: "Rapido Shampoing 5L",
    },
    {
        id: 19,
        image: "images/products/Special Laine et Assouplissant 1L.jpg",
        title: "Lot: Alto Spécial Laine 5L + Assouplissant 1L",
    },
    {
        id: 20,
        image: "images/products/Air Fraiche.jpg",
        title: "Alto Air Fraiche 30ml carton de 20",
    },
    {
        id: 21,
        image: "images/products/Dose Grésil Concentré.jpg",
        title: "Alto Dose Concentré Grezil 120ml coffre de 24: 6 Parfums [Roser, Violette, Lavande, Pin, Full, Citron",
    },
    {
        id: 22,
        image: "images/products/Special Laine.jpg",
        title: "Alto Spécial Laine 5L",
    },
    {
        id: 23,
        image: "images/products/Semi Automatique 5L.jpg",
        title: "Alto semi Automatique 5L",
    },
    {
        id: 24,
        image: "images/products/Vitre Pistolet.jpg",
        title: "Alto Vitre Pistolet 500ml carton de 12",
    },
];

export default productsData;